version: '3'

services:
  elixir-dev:
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    environment:
      - PROJECT=${PROJECT}

    depends_on: 
      - db

    volumes:
      - './src:/home/elixir/app'

    expose:
      - '4000'

    ports:
      - '4000:4000'

    networks:
      - backend
      - frontend

  db:
    restart: always
    image: postgres:latest
    volumes:
      - './postgresql/data:/var/lib/postgresql/data'

    expose:
      - '5432'

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=localhost
    networks:
      - backend

networks:
  backend:
  frontend:
