#!/bin/bash

if test -z "$PROJECT"
  then
    echo "STARTING IEX SHELL FOR PROJECT ${PROJECT || 'PLEASE PROVIDE ENV-VAR <PROJECT>'}"
    exit 1
fi

WDIR=/home/elixir/app/$PROJECT

echo "RUNNING CONTAINER IN '$PROJECT'"

cd $WDIR
iex -S mix phx.server
